"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { buildEntryModel, type Table } from "@/lib/notebook/entryModel";
import { exportFileBase, generateJson, renderMarkdown } from "@/lib/notebook/generateEntry";
import { useBenchStore } from "@/lib/store/benchStore";
import { useHydratedBenchStore } from "@/lib/store/useHydrated";

function download(filename: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for browsers/contexts without the async clipboard API.
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    ta.remove();
    return ok;
  }
}

/** Generated notebook entry + exports (brief §12, §13). */
export function EntryClient({ sessionId }: { sessionId: string }) {
  const hydrated = useHydratedBenchStore();
  const session = useBenchStore((s) => s.sessions.find((x) => x.id === sessionId));
  const activeId = useBenchStore((s) => s.activeSessionId);
  const [copied, setCopied] = useState<"idle" | "ok" | "fail">("idle");
  const model = useMemo(() => (session ? buildEntryModel(session) : null), [session]);

  if (!hydrated) return <main className="p-8 text-muted">Loading…</main>;
  if (!session || !model) {
    return (
      <main className="mx-auto flex max-w-2xl flex-col gap-4 px-6 py-16">
        <h1 className="text-2xl font-semibold">Notebook entry not found</h1>
        <p className="text-muted">It may have been deleted, or it was recorded in a different browser. Entries are stored only in the browser that ran the session.</p>
        <Link href="/" className="text-accent underline">
          Home
        </Link>
      </main>
    );
  }

  const markdown = renderMarkdown(model);
  const base = exportFileBase(session);
  const s = model.summary;

  return (
    <main className="entry-page mx-auto flex w-full max-w-5xl flex-col gap-8 px-4 py-8 sm:px-6">
      <nav className="no-print flex flex-wrap items-center gap-3">
        <Link href="/" className="text-sm text-muted hover:text-accent">
          ← Home
        </Link>
        {!session.endedAt && session.id === activeId && (
          <Link href="/bench" className="ml-2 rounded-lg bg-accent px-3 py-1 text-sm font-semibold text-white dark:text-black">
            Session still in progress: resume
          </Link>
        )}
        <div className="ml-auto flex flex-wrap gap-2">
          <ActionButton
            onClick={async () => {
              setCopied((await copyText(markdown)) ? "ok" : "fail");
              setTimeout(() => setCopied("idle"), 2500);
            }}
          >
            {copied === "ok" ? "Copied ✓" : copied === "fail" ? "Copy failed" : "Copy Markdown"}
          </ActionButton>
          <ActionButton onClick={() => download(`${base}.md`, markdown, "text/markdown;charset=utf-8")}>Download .md</ActionButton>
          <ActionButton onClick={() => download(`${base}.json`, generateJson(session), "application/json")}>Download JSON</ActionButton>
          <ActionButton onClick={() => window.print()} primary>
            Print / Save as PDF
          </ActionButton>
        </div>
      </nav>

      <header className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{model.title}</h1>
        <dl className="flex flex-wrap gap-x-6 gap-y-1 text-muted">
          <Meta label="Date" value={model.header.date} />
          <Meta label="Researcher" value={model.header.researcher} />
          <Meta label="Duration" value={model.header.duration} />
          <Meta label="Started" value={model.header.started} />
          <Meta label="Ended" value={model.header.ended} />
          <Meta label="Samples" value={model.header.samples} />
          <Meta label="Generated by" value="BenchMate (voice session)" />
        </dl>
      </header>

      <section aria-label="Summary" className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Stat label="Steps completed" value={`${s.stepsCompleted} / ${s.totalSteps}`} />
        <Stat label="Measurements" value={s.measurements} />
        <Stat label="Deviations" value={s.deviations} tone={s.deviations ? "warn" : undefined} />
        <Stat label="Observations" value={s.observations} />
        <Stat label="Voided" value={s.voided} />
        <Stat label="Not read back" value={s.unconfirmed} tone={s.unconfirmed ? "warn" : undefined} />
      </section>

      <Section title="Deviations">
        <EntryTable table={model.deviations} />
      </Section>
      <Section title="Measurements">
        <EntryTable table={model.measurements} monoCols={[2]} />
      </Section>
      <Section title="Observations">
        <EntryTable table={model.observations} />
      </Section>
      {model.hasUnconfirmedInTables && (
        <p className="-mt-4 text-sm text-warn">† Not read back to the researcher (the reply was interrupted). Check before relying on it.</p>
      )}
      <Section title="Step log">
        <EntryTable table={model.stepLog} />
      </Section>
      <Section title="Timers">
        <EntryTable table={model.timers} />
      </Section>

      <Section title="Audit">
        <h3 className="font-semibold">Voided entries</h3>
        <EntryTable table={model.voided} strike />
        <h3 className="mt-4 font-semibold">Unconfirmed entries</h3>
        <EntryTable table={model.unconfirmed} />
        <h3 className="mt-4 font-semibold">Source utterances</h3>
        {model.sourceUtterances.length ? (
          <ul className="list-disc space-y-1 pl-5 text-sm">
            {model.sourceUtterances.map((u, i) => (
              <li key={i}>{u}</li>
            ))}
          </ul>
        ) : (
          <p className="text-muted">None.</p>
        )}
      </Section>

      <Section title="Appendix: full transcript">
        {model.transcript.length ? (
          <ol className="transcript max-h-96 overflow-y-auto rounded-xl border border-border bg-surface p-4 font-mono text-sm leading-6">
            {model.transcript.map((l, i) => (
              <li key={i}>{l}</li>
            ))}
          </ol>
        ) : (
          <p className="text-muted">No transcript.</p>
        )}
      </Section>

      <footer className="flex flex-col gap-3 border-t border-border pt-4 text-sm text-muted">
        <p>AssemblyAI session IDs: {model.sessionIds.length ? model.sessionIds.join(", ") : "—"}</p>
        <div>
          <p className="font-semibold text-text">Protocol snapshot</p>
          <ol className="mt-1 space-y-0.5">
            {model.protocolSnapshot.map((l, i) => (
              <li key={i}>{l}</li>
            ))}
          </ol>
        </div>
      </footer>
    </main>
  );
}

function ActionButton({ children, onClick, primary }: { children: React.ReactNode; onClick: () => void; primary?: boolean }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`min-h-12 rounded-xl px-4 font-semibold ${primary ? "bg-accent text-white dark:text-black" : "border-2 border-border hover:border-accent"}`}
    >
      {children}
    </button>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-1.5">
      <dt className="font-semibold text-text">{label}:</dt>
      <dd>{value}</dd>
    </div>
  );
}

function Stat({ label, value, tone }: { label: string; value: string | number; tone?: "warn" }) {
  return (
    <div className={`stat rounded-2xl border bg-surface p-4 ${tone === "warn" ? "border-warn" : "border-border"}`}>
      <p className="text-sm text-muted">{label}</p>
      <p className="font-mono text-2xl font-semibold">{value}</p>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-xl font-semibold">{title}</h2>
      {children}
    </section>
  );
}

function EntryTable({ table, monoCols = [], strike = false }: { table: Table; monoCols?: number[]; strike?: boolean }) {
  if (table.rows.length === 0) return <p className="text-muted">None.</p>;
  return (
    <div className="overflow-x-auto rounded-xl border border-border">
      <table className="w-full border-collapse text-left text-sm">
        <thead className="bg-surface-2">
          <tr>
            {table.headers.map((h) => (
              <th key={h} scope="col" className="whitespace-nowrap px-3 py-2 font-semibold">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {table.rows.map((row, i) => (
            <tr key={i} className="border-t border-border">
              {row.map((c, j) => (
                <td key={j} className={`px-3 py-2 align-top ${monoCols.includes(j) ? "font-mono" : ""} ${strike && j === 2 ? "line-through opacity-70" : ""}`}>
                  {c}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
