import type { BenchSession } from "@/lib/store/types";
import { buildEntryModel, type EntryModel, type EntryOptions, type Table } from "./entryModel";

// Markdown + JSON exports of the notebook entry (brief §13). Deterministic:
// same session + time zone → byte-identical output (snapshot-tested).

/** Escape a value for a Markdown table cell. */
export function cell(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim() || "—";
}

function table(t: Table): string {
  if (t.rows.length === 0) return "_None._";
  const head = `| ${t.headers.map(cell).join(" | ")} |`;
  const sep = `|${t.headers.map(() => "---").join("|")}|`;
  const body = t.rows.map((r) => `| ${r.map(cell).join(" | ")} |`);
  return [head, sep, ...body].join("\n");
}

export function renderMarkdown(m: EntryModel): string {
  const s = m.summary;
  const out: string[] = [
    `# ${m.title}`,
    `**Date:** ${m.header.date} · **Researcher:** ${m.header.researcher} · **Duration:** ${m.header.duration}  `,
    `**Started:** ${m.header.started} · **Ended:** ${m.header.ended} · **Generated by:** BenchMate (voice session)  `,
    `**Samples:** ${m.header.samples}`,
    "",
    "## Summary",
    `- Steps completed: ${s.stepsCompleted} of ${s.totalSteps}`,
    `- Measurements: ${s.measurements} · Deviations: ${s.deviations} · Observations: ${s.observations} · Voided entries: ${s.voided}`,
    `- Unconfirmed entries (not read back): ${s.unconfirmed}`,
    "",
    "## Deviations",
    table(m.deviations),
    "",
    "## Measurements",
    table(m.measurements),
    "",
    "## Observations",
    table(m.observations),
    "",
  ];
  if (m.hasUnconfirmedInTables) out.push("† Not read back to the researcher (the reply was interrupted). Check before relying on it.", "");
  out.push(
    "## Step log",
    table(m.stepLog),
    "",
    "## Timers",
    table(m.timers),
    "",
    "## Audit",
    "### Voided entries",
    table(m.voided),
    "",
    "### Unconfirmed entries",
    table(m.unconfirmed),
    "",
    "### Source utterances",
    m.sourceUtterances.length ? m.sourceUtterances.map((u) => `- ${u}`).join("\n") : "_None._",
    "",
    "## Appendix: full transcript",
    m.transcript.length ? m.transcript.map((l) => `${l}  `).join("\n") : "_No transcript._",
    "",
    "---",
    `AssemblyAI session IDs: ${m.sessionIds.length ? m.sessionIds.join(", ") : "—"}`,
    "",
    "Protocol snapshot:",
    "",
    ...m.protocolSnapshot,
    "",
  );
  return out.join("\n");
}

export function generateMarkdown(session: BenchSession, opts?: EntryOptions): string {
  return renderMarkdown(buildEntryModel(session, opts));
}

/** Full raw session for archiving/re-analysis. */
export function generateJson(session: BenchSession): string {
  return `${JSON.stringify({ format: "benchmate-session", version: 1, exportedAt: new Date().toISOString(), session }, null, 2)}\n`;
}

/** "2026-09-26-plasmid-dna-miniprep" style base filename. */
export function exportFileBase(session: BenchSession): string {
  const slug = session.protocol.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
  return `${session.startedAt.slice(0, 10)}-${slug || "benchmate-session"}`;
}
